#define TUKLIB_SYMBOL_PREFIX lzma_
#define HAVE_IMMINTRIN_H
#define HAVE__MM_MOVEMASK_EPI8
#define HAVE_USABLE_CLMUL
#define HAVE_VISIBILITY 0
#define PACKAGE_NAME "XZ Utils"
#define PACKAGE_BUGREPORT "xz@tukaani.org"
#define PACKAGE_URL "https://tukaani.org/xz/"
#define HAVE_STDBOOL_H
#define HAVE__BOOL
#define HAVE_STDINT_H
#define HAVE_INTTYPES_H
#define HAVE_CHECK_CRC32
#define TUKLIB_FAST_UNALIGNED_ACCESS
#define HAVE___BUILTIN_ASSUME_ALIGNED
#define HAVE_CHECK_CRC64
#define HAVE_CHECK_SHA256
#define HAVE_MF_HC3
#define HAVE_MF_HC4
#define HAVE_MF_BT2
#define HAVE_MF_BT3
#define HAVE_MF_BT4
#define MYTHREAD_VISTA
#define HAVE_ENCODER_LZMA1
#define HAVE_ENCODER_LZMA2
#define HAVE_ENCODER_DELTA
#define HAVE_ENCODER_X86
#define HAVE_ENCODER_ARM
#define HAVE_ENCODER_ARMTHUMB
#define HAVE_ENCODER_ARM64
#define HAVE_ENCODER_POWERPC
#define HAVE_ENCODER_IA64
#define HAVE_ENCODER_SPARC
#define HAVE_ENCODER_RISCV
#define HAVE_ENCODERS
#define HAVE_DECODER_LZMA1
#define HAVE_DECODER_LZMA2
#define HAVE_DECODER_DELTA
#define HAVE_DECODER_X86
#define HAVE_DECODER_ARM
#define HAVE_DECODER_ARMTHUMB
#define HAVE_DECODER_ARM64
#define HAVE_DECODER_POWERPC
#define HAVE_DECODER_IA64
#define HAVE_DECODER_SPARC
#define HAVE_DECODER_RISCV
#define HAVE_DECODERS
#define HAVE_LZIP_DECODER
